import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { fetchMaintenance } from "../api/client";
import type { MaintenanceResponse } from "../types/maintenance";
import StatusBadge from "../components/StatusBadge";
import SectionCard from "../components/SectionCard";
import LoadingState from "../components/LoadingState";
import ErrorState from "../components/ErrorState";

function priorityClass(priority: string): string {
  return `priority-badge priority-${priority.toLowerCase()}`;
}

export default function Maintenance() {
  const navigate = useNavigate();
  const [udiInput, setUdiInput] = useState("7012");
  const [selectedUdi, setSelectedUdi] = useState(7012);
  const [maintenance, setMaintenance] = useState<MaintenanceResponse | null>(
    null
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;

    async function loadMaintenance() {
      setLoading(true);
      setError(null);

      try {
        const data = await fetchMaintenance(selectedUdi);

        if (active) {
          setMaintenance(data);
        }
      } catch (requestError: unknown) {
        if (active) {
          const axiosError = requestError as {
            response?: { status?: number; data?: { detail?: string } };
            message?: string;
          };

          if (axiosError.response?.status === 404) {
            setError(
              `UDI ${selectedUdi} was not found in the Phase-II monitoring dataset.`
            );
          } else {
            setError(
              axiosError.response?.data?.detail ??
                axiosError.message ??
                "Unable to load maintenance recommendations."
            );
          }
        }
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    }

    loadMaintenance();

    return () => {
      active = false;
    };
  }, [selectedUdi]);

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const parsedUdi = Number(udiInput);

    if (!Number.isInteger(parsedUdi) || parsedUdi <= 0) {
      setError("Please enter a valid positive integer UDI.");
      return;
    }

    setSelectedUdi(parsedUdi);
  }

  return (
    <div>
      <div className="content-page-title">Maintenance Recommendations</div>
      <div className="content-page-subtitle">
        Deterministic evidence-based recommendations generated by the existing
        Python maintenance recommendation module.
      </div>

      <form className="lookup-row" onSubmit={handleSubmit}>
        <input
          type="number"
          min="1"
          value={udiInput}
          onChange={(event) => setUdiInput(event.target.value)}
          placeholder="Enter Phase-II UDI"
        />
        <button type="submit">Load Recommendation</button>
      </form>

      {loading ? (
        <LoadingState message="Loading maintenance recommendation..." />
      ) : error || !maintenance ? (
        <ErrorState
          message={error ?? "Maintenance recommendation is unavailable."}
        />
      ) : (
        <>
          <div className="maintenance-summary">
            <span>UDI {maintenance.udi}</span>
            <StatusBadge status={maintenance.health_status} />
            <span className={priorityClass(maintenance.priority)}>
              {maintenance.priority} priority
            </span>
            <button
              type="button"
              className="secondary-button"
              onClick={() => navigate(`/machine/${maintenance.udi}`)}
            >
              View Machine Health
            </button>
          </div>

          <SectionCard
            title="Primary Recommendation"
            caption="Returned directly from FastAPI. React does not generate maintenance actions."
          >
            <div className="recommendation-panel">
              <div className="recommendation-label">Recommended Action</div>
              <p className="recommendation-primary">
                {maintenance.primary_recommendation}
              </p>

              {maintenance.additional_recommendations.length > 0 ? (
                <>
                  <div className="recommendation-label">
                    Additional Investigation Actions
                  </div>
                  <ul className="bullet-list">
                    {maintenance.additional_recommendations.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                </>
              ) : null}
            </div>
          </SectionCard>

          <div className="analytics-grid">
            <SectionCard
              title="Contributing Sensors"
              caption="Extreme standardized sensor signals associated with the multivariate abnormal state; not causal findings."
            >
              {maintenance.contributing_sensors.length > 0 ? (
                <div className="contributor-grid">
                  {maintenance.contributing_sensors.map((sensor) => (
                    <article
                      key={sensor.sensor}
                      className={`contributor-card contributor-${sensor.direction.toLowerCase()}`}
                    >
                      <div className="contributor-label">{sensor.sensor}</div>
                      <div className="contributor-value">
                        {sensor.z_score >= 0 ? "+" : ""}
                        {sensor.z_score.toFixed(4)} SD
                      </div>
                      <div className="contributor-caption">
                        {sensor.direction} standardized signal
                      </div>
                    </article>
                  ))}
                </div>
              ) : (
                <p className="empty-inline">
                  No individual standardized sensor signal exceeded the
                  diagnostic threshold.
                </p>
              )}
            </SectionCard>

            <SectionCard title="Statistical Evidence">
              <ul className="bullet-list">
                {maintenance.evidence.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </SectionCard>
          </div>

          <SectionCard title="Limitations">
            <div className="warning-panel">
              <strong>Operational recommendation, not physical diagnosis</strong>
              <p>
                The recommendations support inspection and investigation. They
                do not confirm machine fault, failure cause, or guaranteed
                future failure.
              </p>
            </div>

            <ul className="bullet-list muted-list">
              {maintenance.limitations.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </SectionCard>
        </>
      )}
    </div>
  );
}
